### ISSUE TITLE
please continue this plugin

### ISSUE THREAD

**Issue by Mrs-Feathers** [Pommesritter/TownyPlots#1]
i just wanted to say how awesome this plugin is for town building and RPG servers and i'd really love to use this in my server.. but i see its been dead since 2014. please keep working on this.. if there's any way i can help, let me know.

**Comment by Pommesritter** [comment]
Greetings,

huh, that is interesting.

Actually i am studying "computer sience" at the moment and still thinking
about creating more of such open source content.

You can look up "herbertsfundgrube" (->https://github.com/herbertsfundgrube/GSplugin) if you want. There you can find
another Plugin I created with a friend.

I could compile it for you, so you can test it. :)

Regardful
"Herbert" :D




Am Fr., 2. Nov. 2018, 05:14 hat Katja DeCuir <notifications@github.com>
geschrieben:

**Comment by Pommesritter** [comment]
https://www.dropbox.com/sh/034vsopzoaam9jn/AACUQaIICNq7uAUrsFFqMxfta?dl=0

Please tell me if you can open this file. It should work on newest Bukkit/towny most likely.

**Comment by Mrs-Feathers** [comment]
awesome! i'm going to test it now!

**Comment by Mrs-Feathers** [comment]
it does not work. i am able to assign plots to be certain plots.. but after setting one to a wheat farm with the command /plottype farm ... and then adding chests for /b addchest input [and putting a diamond hoe in it] and the other /b addchest output... in a a grassy field [it didn't do anything so i also tilled dirt into soil and planted some wheat to see if it would at least pick it up..] and it's not done anything. lumberman's hut does the same, nothing... and mine acts weird in that i can't assign it a chest because it tells me "that is not a chest" every time. and it shows this in console: [15:54:58 ERROR]: Could not pass event PlayerInteractEvent to TownyPlots v0.3
org.bukkit.event.EventException: null



`[15:53:59 INFO]: Miss_Moth issued server command: /plottype lumberhut
[15:53:59 WARN]: Exception in thread "Thread-19" 
[15:53:59 WARN]: java.lang.NullPointerException
[15:53:59 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.util.CraftLegacy.getMaterial(CraftLegacy.java:225)
[15:53:59 WARN]: 	at me.kleinerminer.townyplots.building.Lumberhut.refreshLevel(Lumberhut.java:67)
[15:53:59 WARN]: 	at me.kleinerminer.townyplots.threads.BuildingWork.lumberhutWork(BuildingWork.java:117)
[15:53:59 WARN]: 	at me.kleinerminer.townyplots.threads.BuildingWork.run(BuildingWork.java:48)
[15:54:07 INFO]: Miss_Moth issued server command: /b addchest output
[15:54:09 ERROR]: Could not pass event PlayerInteractEvent to TownyPlots v0.3
org.bukkit.event.EventException: null
`

**Comment by Mrs-Feathers** [comment]
[15:54:28 INFO]: Miss_Moth issued server command: /plottype mine
[15:54:28 ERROR]: Fatal error trying to convert TownyPlots v0.3:me/kleinerminer/townyplots/building/Mine.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for RAIL. Did you forget to define api-version: 1.13 in your plugin.yml?

also this.

**Comment by Mrs-Feathers** [comment]
also, as a suggestion to make it more.. "fluid" with towny, you could have towny automatically set the plot type in it so you see that you've walked into a farm or something. then again, that's not really an issue, just a suggestion to make it nicer. 

though, another thing, it'd be amazing to spawn a blueprint as well, once the player sets it as a type.

**Comment by Pommesritter** [comment]
You could aswell check [this](https://gitlab.com/herbertsfundgrube/civitasserver)

**Comment by Pommesritter** [comment]
yes, they changed something about the MATERIAL enum. Thats why rails, soil and crops are not properly described in TownyPlots for 1.13.

**Comment by Mrs-Feathers** [comment]
> You could aswell check [this](https://gitlab.com/herbertsfundgrube/civitasserver)

thats pretty neat! i dont think i'm able to use something like that just yet in my server, but that is pretty cool.



> yes, they changed something about the MATERIAL enum. Thats why rails, soil and crops are not properly described in TownyPlots for 1.13.

ahh. that makes sense.

**Comment by Pommesritter** [comment]
Did you define 'api-version: 1.13' in your plugin.yml?

**Comment by Pommesritter** [comment]
I redone some stuff and added a debugger.
Pls try the same again and tell me what kind of error msg you get. Also remember to check your config.

> https://www.dropbox.com/sh/034vsopzoaam9jn/AACUQaIICNq7uAUrsFFqMxfta?dl=0

I will add a .jar download link to the repo. Refer to this file as to the newest version.

**Comment by Pommesritter** [comment]
New readme: https://github.com/Pommesritter/TownyPlots/blob/master/README.md

**Comment by Pommesritter** [comment]
Another update. Keep track of [main page](https://github.com/Pommesritter/TownyPlots) and [download section](https://github.com/Pommesritter/TownyPlots/tree/master/downloads) please.

**Comment by Skizzles** [comment]
Wish this was continued!
